#!/usr/bin/env bash
# A script that installs nginx


apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i 's/^listen\s*\(.*\)\s*default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default
service nginx start
