#!/usr/bin/env bash
# A script that redirects to another page

apt-get -y update
apt-get -y install nginx

new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
service nginx restart

