#!/usr/bin/env bash
#Install and configure HAproxy on lb-01 server to send traffic to web-01 and web-02

sudo apt-get -y update
apt-get -y install haproxy

haproxy_config="
frontend anttesdev_frontend
    bind *:80
    mode http

    # Distribute requests using roundrobin algorithm
    default_backend anttesdev_backend

backend anttesdev_backend
    mode http
    balance roundrobin

    # Define backend servers
    server 468973-web-01 54.160.90.166:80 check
    server 468973-web-02 100.25.222.73:80 check
"

echo "$haproxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
