#!/usr/bin/env bash
# A Bash script that pings an IP address passed as an argument 5 times

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

ip_address="$1"

ping -c 5 "$ip_address"


