#!/usr/bin/env bash
#A script that configures Nginx to run, and listening on port 80 of all the server’s active IPv4 IPs
sudo rm -rf /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
sudo service nginx restart

