#!/usr/bin/env bash
# Bash script to display numbers from 1 to 20 and special messages based on specific iterations

counter=1
while [ $counter -le 20 ]; do
 case $counter in
        4)
	 echo "$counter"
            echo "bad luck from China"
            ;;
	9)
	echo "$counter"
            echo "bad luck from Japan"
            ;;
	17)
	echo "$counter"
            echo "bad luck from Italy"
            ;;
	*)
	echo "$counter"
            ;;
    esac
((counter++))
done
