#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server
#localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/new_host
echo "127.0.0.2		localhost" > ~/new_host
echo "8.8.8.8		facebook.com" >> ~/new_host
cp -f ~/new_host /etc/hosts
