#!/usr/bin/env bash
# A scrpit that runs nginx as the nginx instead of root inorder to protect the webserver
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start

